apiVersion: apps/v1
kind: Deployment
metadata:
  name: personal-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: personal
  template:
    metadata:
      labels:
        app: personal
    spec:
      containers:
        - name: personal
          image: gyan0621/personal
          env:
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NATS_URL
              value: 'http://nats-srv:4222'
            - name: NATS_CLUSTER_ID
              value: remd
            - name: MONGO_URI
              value: 'mongodb://posts-mongo-srv:27017/personal'
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: personal-srv
spec:
  selector:
    app: personal
  ports:
    - name: personal
      protocol: TCP
      port: 3000
      targetPort: 3000
